### ISSUE TITLE
Not working on 1.16.4 because adding Output Images:true doesnt work

### ISSUE THREAD

**Issue by xNorbig** [Keristero/voxel-map-image-combiner#3]
When I add `Output Images:true` into `.minecraft/config/voxelmap.properties` and then launch Minecraft, the line automatically disappears, so `.minecraft/voxelmap/cache/<my server ip>\overworld` doesnt have any folders, only region zip files.

**Comment by Keristero** [comment]
I think I've had this issue in the past, try adding it again after launching.
Otherwise I think this may be dead :( 
maybe you can use mineways or something to generate a map image? please let me know if you find an alternative.

**Comment by magicus** [comment]
At first I thought it was broken too, but voxelmap will honor the Output Images line, but remove it! See the instructions at MamiyaOtaru repo: https://github.com/MamiyaOtaru/anvilmapper

@Keristero Yuo may want to update your instructions to make it clear that:

a) the line will disappear after each and every run, and

b) you need to view the map and pan around to generate images, and

c) you need to leave the world to have voxelmap actually write them down to disk.

**Comment by Keristero** [comment]
I've updated the instructions with your recommendations magicus, thanks.
